package:
  name: libqglviewer
  version: 2.6.4

source:
  git_url: https://github.com/GillesDebunne/libQGLViewer
  git_tag: v2.6.4
  patches:
   # List any patch files here
   - QGLViewer_pro.patch
   - examples.pri.patch
   - libQGLViewer.pro.patch

build:
  number: 1
  features:
    - vc9     [win and py27]
    - vc14    [win and py37]

requirements:
  build:
    - python
    - qt =5
    - patch
  run:
    - qt =5
    - vs2008_runtime   [win and py27]
    - vs2015_runtime   [win and py37]

about:
  home: http://www.libqglviewer.com
  license: GPL
